.\" Copyright (c) 2008-2010 Joshua R. Elsasser.
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd April 5, 2010
.Dt UPART 8
.Os
.Sh NAME
.Nm upart
.Nd a utility for reading partition maps in various formats
.Sh SYNOPSIS
.Bk -words
.Nm upart
.Op Fl fhlqrsvVx
.Op Fl C Ar cylinders
.Op Fl H Ar heads
.Op Fl L Ar label
.Op Fl S Ar sectors
.Op Fl w Ar file
.Op Fl z Ar size
.Ar path
.Ek
.Sh DESCRIPTION
The
.Nm
utility can be used to read partition information from a disk. The
following partition schemes are supported, and may be nested:
.Pp
.Bl -tag -width disklabelXXX -compact
.It Em APM
Apple partition map. Used on Apple 68k and PowerPC systems.
.It Em Disklabel
BSD disklabel. Used by several BSD-derived systems on various platforms.
.It Em GPT
EFI GUID partition table. Used on EFI-based systems.
.It Em MBR
PC-style MBR. Used on several platforms. Extended partitions are supported.
.It Em Sun label
Sun disk label. Both SPARC and x86 formats are supported. Both Sun
VTOC and OpenBSD extensions to the SPARC format are supprted as well.
.El
.Pp
The options are as follows:
.Bl -tag -width Ds
.It Xo Fl C Ar cylinders
.Fl H Ar heads Fl S Ar sects
.Xc
Specify an alternate geometry for the disk. This is useful if the
geometry could not be determined automatically, or is incorrect.
.It Fl f
Indicate that
.Ar path
is a plain file, and not a device node.
.It Fl h
Format sizes in a more human-readable fashion.
.It Fl l
List available disk device names and exit.
.It Fl L Ar label
A text label to save with an image created with
.Ar w ,
the default is the full device path. The label will be truncated to
255 characters if it is longer.
.It Fl q
Show less information when reading, parsing, and printing partition
maps. Additional
.Fl q
options decrease the verbosity level further.
.It Fl r
Relax some checks when parsing partition maps. This may be useful to
extract information out of a partially corrupted map.
.It Fl s
Swap the start and size columns of the partition display.
.It Fl v
Show more information when reading, parsing, and printing partition
maps. Additional
.Fl v
options increase the verbosity level further.
.It Fl V
Display the version of
.Nm
and exit.
.It Fl w Ar file
Save partition information for the disk to
.Ar file
in a compact binary image format. The image may later be read by
.Nm
as if it were the original disk.
.It Fl x
Display numbers in hexadecimal (base 16).
.It Fl z Ar size
Specify an alternative sector size in bytes.
.El
.Sh AUTHORS
.An -nosplit
The
.Nm
program was written by
.An Joshua Elsasser Aq joshua@elsasser.org .
